-- Eksekusi skrip ini di "SQL Editor" pada dashboard Supabase (Coolify) Anda yang baru.

-- 1. Table: users
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "phoneNumber" TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  name TEXT,
  package TEXT DEFAULT 'free',
  "packageExpiresAt" TIMESTAMP WITH TIME ZONE,
  "partnerPhone" TEXT,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Table: transactions
CREATE TABLE IF NOT EXISTS public.transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  type TEXT NOT NULL CHECK (type IN ('income', 'expense')),
  amount NUMERIC NOT NULL,
  category TEXT NOT NULL,
  description TEXT,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  "deletedAt" TIMESTAMP WITH TIME ZONE
);

-- 3. Table: payments
CREATE TABLE IF NOT EXISTS public.payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  package TEXT NOT NULL,
  amount NUMERIC NOT NULL,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Set RLS (Row Level Security) ke false atau buat policy (Jika ingin diakses lewat anon key).
-- Tapi karena backend Anda menggunakan service_role key, RLS tidak masalah karena service_role akan membypass RLS.
